### ISSUE TITLE
Translate documentation

### ISSUE THREAD

**Issue by goiblas** [goiblas/Heliblocks-App#10]
Translate a documentation page from Spanish to English

* You don't need know to code
* The documentation use markdown syntax
* You can contribute by editing from github https://github.com/goiblas/Heliblocks-App/edit/master/src/pages/documentation/docs-en.js

**Comment by mohandas-pai** [comment]
Hi, i have raised a pull request for the initial version of the transation, let me know if i have missed something

**Comment by goiblas** [comment]
Looks good, thanks for contributing

**Comment by mohandas-pai** [comment]
Thank you, glad i could help
